### ISSUE TITLE
User Signup & Login

### ISSUE THREAD

**Issue by maethub** [MCSPitaya/PitayaClient#13]
User Story: As a lawyer, I want to sign up / login to my own account so that only I can access confidential case files

**Comment by ksmonkey123** [comment]
The authentication API specification is available under: https://github.com/MCSPitaya/PitayaServer/wiki/Authentication

**Comment by maethub** [comment]
User Signup is being done in the backend, Login is completed!

**Comment by ksmonkey123** [comment]
user signup is a firm function now under /api/firm/addUser. so front-end user signup is possible

**Comment by ksmonkey123** [comment]
https://github.com/MCSPitaya/PitayaServer/wiki/User-and-Firm-API#23-adding-users
